
set(TOOL_CHAIN_PRE_PATH public/cmake/toolchains)

if(HWM)

    if(HWM STREQUAL "CCE1")
        set(CMAKE_TOOLCHAIN_FILE ${TOOL_CHAIN_PRE_PATH}/mips64_gcc452_glibc2130.cmake)
        set(CUR_CFG_FILE public/cmake/hwm/cce1_cfg.cmake)
    elseif(HWM STREQUAL "BPN")
        set(CMAKE_TOOLCHAIN_FILE ${TOOL_CHAIN_PRE_PATH}/armeb_eabi_gcc452_glibc2130_be8.cmake)
        set(CUR_CFG_FILE public/cmake/hwm/bpn_cfg.cmake)
    elseif(HWM STREQUAL "VSW")
        set(CMAKE_TOOLCHAIN_FILE ${TOOL_CHAIN_PRE_PATH}/ppc64_gcc4.8.2_glibc2.18.0_multi.cmake)
        set(CUR_CFG_FILE public/cmake/hwm/vsw_cfg.cmake)
    elseif(HWM STREQUAL "VBP")
        set(CMAKE_TOOLCHAIN_FILE ${TOOL_CHAIN_PRE_PATH}/ppc64_gcc4.8.2_glibc2.18.0_multi.cmake)
        set(CUR_CFG_FILE public/cmake/hwm/vbp_cfg.cmake)
    endif()

elseif(VBS)

    if(VBS STREQUAL "VBPN_PLAT")
        set(CMAKE_TOOLCHAIN_FILE ${TOOL_CHAIN_PRE_PATH}/armeb_eabi_gcc452_glibc2130_be8.cmake)
        set(CUR_CFG_FILE public/cmake/vbs/vbpn_plat_cfg.cmake)
    elseif(VBS STREQUAL "OAMBS")
        set(CMAKE_TOOLCHAIN_FILE ${TOOL_CHAIN_PRE_PATH}/x86_64_gcc_4_8.cmake)
        set(CUR_CFG_FILE public/cmake/vbs/oam_bs_cfg.cmake)
    elseif(VBS STREQUAL "X86_64_S")
        set(CMAKE_TOOLCHAIN_FILE ${TOOL_CHAIN_PRE_PATH}/x86_64_gcc_4_8.cmake)
        set(CUR_CFG_FILE public/cmake/vbs/x86_64_s_cfg.cmake)        
    elseif(VBS STREQUAL "VBP_PLAT")
        set(CMAKE_TOOLCHAIN_FILE ${TOOL_CHAIN_PRE_PATH}/armeb_eabi_gcc482_glibc2.18.0_be8.cmake)
        set(CUR_CFG_FILE public/cmake/vbs/vbp_plat_cfg.cmake)
    elseif(VBS STREQUAL "VBP_APP")
        set(CMAKE_TOOLCHAIN_FILE ${TOOL_CHAIN_PRE_PATH}/armeb_eabi_gcc482_glibc2.18.0_be8.cmake)
        set(CUR_CFG_FILE public/cmake/vbs/vbp_app_cfg.cmake)
    elseif(VBS STREQUAL "VBP_PLAT_SIMU")
        set(CMAKE_TOOLCHAIN_FILE ${TOOL_CHAIN_PRE_PATH}/x86_64_gcc_4_8.cmake)
        set(CUR_CFG_FILE public/cmake/vbs/vbp_simu_plat_cfg.cmake)
    elseif(VBS STREQUAL "VBP_APP_SIMU")
        set(CMAKE_TOOLCHAIN_FILE ${TOOL_CHAIN_PRE_PATH}/x86_64_gcc_4_8.cmake)
        set(CUR_CFG_FILE public/cmake/vbs/vbp_simu_app_cfg.cmake)
    endif()

elseif(UNIT_TEST)
    set(CMAKE_TOOLCHAIN_FILE public/cmake/unittest/ubuntu_16_04_toolchains.cmake)
    set(CUR_CFG_FILE public/cmake/unittest/oss_vplat_16_04_cfg.cmake)
endif()

